name: model
dependencies:
  - spacy<3.5.0,>=3.4.2
  - inflect
  - python>=3.9
  - pip
  - ipython         # dev
  - scikit-learn    # dev
  - pandas          # dev
  - colorama        # dev
  - pip:
    - pyspellchecker<=0.5.5
    - word2number
    - python-dotenv # dev