name: 'coverage'

#on:
#    pull_request:
#        branches:
#            - main
on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.9", "3.10"]
        include:
          - os: ubuntu-latest
            CONDA_OS: linux-64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: ${{ matrix.python-version }}
        use-mamba: true
        auto-update-conda: true
        activate-environment: test
    - name: Set up conda and install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        python -m pip install ./dose_instruction_parser[dev]
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        python -m pytest -vv dose_instruction_parser/di_parser/tests --ignore=dose_instruction_parser/di_parser/tests/test_parser.py --cov=dose_instruction_parser/di_parser --cov-report=xml --cov-report=html
