name: Publish Sphinx Documentation
on:
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        include:
          - os: ubuntu-latest
            CONDA_OS: linux-64
      fail-fast: false
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
      - uses: conda-incubator/setup-miniconda@v3
        with:
          python-version: ${{ matrix.python-version }}
          use-mamba: true
          auto-update-conda: true
          activate-environment: test
      - name: Set up conda and install dependencies
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          python -m pip install ./dose_instruction_parser[dev]
      - name: Sphinx build
        shell: bash -l {0}
        run: |
          cd doc/sphinx
          make html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/html
          force_orphan: true
