name: Release Workflow

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensure the full history is fetched so bumpver can work correctly

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bumpver build

    - name: Bump version
      run: |
        NEW_VERSION=${{ github.event.release.tag_name }}
        bumpver update --new-version $NEW_VERSION
      working-directory: dose_instruction_parser

    - name: Commit version bump
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add dose_instruction_parser/pyproject.toml
        git add dose_instruction_parser/dose_instruction_parser/__init__.py
        git add dose_instruction_parser/README.md
        git commit -m "Bump version to $NEW_VERSION"
        git push

    - name: Build package
      run: |
        python -m build
      working-directory: dose_instruction_parser

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
        packages_dir: dose_instruction_parser/dist
      env:
        TWINE_USERNAME: "__token__"
